version: '3'
services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: musa
      LANG: ja_JP.utf8
    ports: 
      - 5432:5432
    volumes:
      - ./docker/postgres/data:/var/lib/postgres/data
    container_name: musa.postgres
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    container_name: musa.redis
  rust:
    build: ./musa_api
    environment:
      CLIENT_ID: $CLIENT_ID
      CLIENT_SECRET: $CLIENT_SECRET
      REDIRECT_URI: $REDIRECT_URI
    ports:
      - 8000:8000
    depends_on:
      - postgres 
    container_name: musa.rust
  nuxt:
    build: ./musa_client
    ports:
      - 3000:3000
    depends_on:
      - rust
    container_name: musa.nuxt
