version: '3.8'
services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    container_name: musa.redis
  rust:
    build: ./musa_api
    image: pyama0327/musa:api
    environment:
      CLIENT_ID: $CLIENT_ID
      CLIENT_SECRET: $CLIENT_SECRET
      REDIRECT_URI: $REDIRECT_URI
      REDIS_URL: musa.redis:6379
    ports:
      - 8000:8000
    depends_on:
      - redis
    container_name: musa.api
  nuxt:
    build: ./musa_client
    image: pyama0327/musa:client
    environment:
      API_BASE_URL: $API_BASE_URL
    ports:
      - 3000:3000
    depends_on:
      - rust
    container_name: musa.client
