version: '3'
services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: musa
      LANG: ja_JP.utf8
    ports: 
      - 5432:5432
    volumes:
      - ./docker/postgres/data:/var/lib/postgres/data
    container_name: musa.postgres
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    container_name: musa.redis
  rust:
    build:
      context: ./musa_api
      dockerfile: Dockerfile-dev
    ports:
      - 8000:8000
    volumes:
      - ./musa_api:/musa_api
    command: cargo watch -x "clippy" -x "run"
    depends_on:
      - postgres 
    container_name: musa.rust
